version: '3.7'
services:
  php8keyheaven:
    container_name: php8keyheaven
    build: ../KeyHeaven_app/docker/php8
    ports:
      - "8000:8000"
    volumes:
      - ./project/:/opt/symfo
    depends_on:
      - database

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  database:
    platform: linux/amd64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: keyheaven
      MYSQL_USER: keyheaven
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: spote
    ports:
      - "8080:80"

volumes:
  db-data:
