version: '3.7'
services:
  php8:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    environment:
      DATABASE_URL: mysql://root:symfony@database/keyheaven?serverVersion=8
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: keyheaven
      MYSQL_USER: keyheaven
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: keyheaven
    ports:
      - "8080:80"

volumes:
  db-data: